name: Build and Push Docker Image

on:
  # Allows this workflow to be reusable
  workflow_call:
    inputs:
      dockerfilePath:
        description: 'Path to the Dockerfile'
        required: false  
        default: './Dockerfile' 
        type: string
      imageName:
        description: 'Name for the Docker image'
        required: true
        type: string
      imageTag:
        description: 'Tag for the Docker image'
        required: true
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.7.1

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3.3.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6.10.0
      with:
        context: .
        file: ${{ inputs.dockerfilePath }}  # Use default value if not specified
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/${{ inputs.imageName }}:${{ inputs.imageTag }}
